[[Raylib]]
arch = "aarch64"
git-tree-sha1 = "9f6f781f4003016851ff7d329d2af9bbe8780453"
os = "macos"

    [[Raylib.download]]
    sha256 = "2c50b7f6d0319aeb463eabff7b86866347f98e2931a48f18365be254795b2bc0"
    url = "https://github.com/JuliaBinaryWrappers/Raylib_jll.jl/releases/download/Raylib-v4.0.0+1/Raylib.v4.0.0.aarch64-apple-darwin.tar.gz"
[[Raylib]]
arch = "aarch64"
git-tree-sha1 = "64bf30ed2fb5053e24d0baa9e2037a082e2c56c5"
libc = "glibc"
os = "linux"

    [[Raylib.download]]
    sha256 = "41cac998e87cd16cb910c35f9282c25ea40caacf9c007750aadc6ff7cdded826"
    url = "https://github.com/JuliaBinaryWrappers/Raylib_jll.jl/releases/download/Raylib-v4.0.0+1/Raylib.v4.0.0.aarch64-linux-gnu.tar.gz"
[[Raylib]]
arch = "aarch64"
git-tree-sha1 = "f8e8f7d04b770ff7b94c6534e3dedb800fce2a06"
libc = "musl"
os = "linux"

    [[Raylib.download]]
    sha256 = "496715d704d1b2a9d117ac3524f334683fce3625d1ddcbb6911864a4abb3b9d7"
    url = "https://github.com/JuliaBinaryWrappers/Raylib_jll.jl/releases/download/Raylib-v4.0.0+1/Raylib.v4.0.0.aarch64-linux-musl.tar.gz"
[[Raylib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d2536cd4c6c78f7026653b384c7c62486356f365"
libc = "glibc"
os = "linux"

    [[Raylib.download]]
    sha256 = "02774f806a85e92475917f060ab6a6876d881a6c3b9a7eda518247934c2fba0d"
    url = "https://github.com/JuliaBinaryWrappers/Raylib_jll.jl/releases/download/Raylib-v4.0.0+1/Raylib.v4.0.0.armv7l-linux-gnueabihf.tar.gz"
[[Raylib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ad0c185f3895fedf13cb900b5f8a73677dc6ae75"
libc = "musl"
os = "linux"

    [[Raylib.download]]
    sha256 = "f9924a4049fd1955deb40173ca3409083921e2e21945d0fc27c661daa70e6ff9"
    url = "https://github.com/JuliaBinaryWrappers/Raylib_jll.jl/releases/download/Raylib-v4.0.0+1/Raylib.v4.0.0.armv7l-linux-musleabihf.tar.gz"
[[Raylib]]
arch = "i686"
git-tree-sha1 = "eaab363a883d5c781d2dbea50e468f6c367754f5"
libc = "glibc"
os = "linux"

    [[Raylib.download]]
    sha256 = "5eee58f67f8f610d2e4aead7cf57967c9ded60cace96a1aefd6f7d9c9a6ca79a"
    url = "https://github.com/JuliaBinaryWrappers/Raylib_jll.jl/releases/download/Raylib-v4.0.0+1/Raylib.v4.0.0.i686-linux-gnu.tar.gz"
[[Raylib]]
arch = "i686"
git-tree-sha1 = "0f4e85b5c89862d00cb74a62f35d3bcb65f80fcf"
libc = "musl"
os = "linux"

    [[Raylib.download]]
    sha256 = "4de6cf8ec7f9f53801df0ed78139ec59ec900fc49aba8a79658af54717b2e3c8"
    url = "https://github.com/JuliaBinaryWrappers/Raylib_jll.jl/releases/download/Raylib-v4.0.0+1/Raylib.v4.0.0.i686-linux-musl.tar.gz"
[[Raylib]]
arch = "powerpc64le"
git-tree-sha1 = "d3f3a5d3cd5c369420fd8c602ebb354cd5aa1f0a"
libc = "glibc"
os = "linux"

    [[Raylib.download]]
    sha256 = "3f4fb50ac0a4709ac254a6ae4b121dc09a237142f3706b7628d90af3ae2fb8da"
    url = "https://github.com/JuliaBinaryWrappers/Raylib_jll.jl/releases/download/Raylib-v4.0.0+1/Raylib.v4.0.0.powerpc64le-linux-gnu.tar.gz"
[[Raylib]]
arch = "x86_64"
git-tree-sha1 = "8e5f081aee50159b8c0edbdecff50862c44a037b"
os = "macos"

    [[Raylib.download]]
    sha256 = "137e8e56c625fe84c2bfb1d4f5fb334127f52ed87dfe1513a27c9b0585ee7f6e"
    url = "https://github.com/JuliaBinaryWrappers/Raylib_jll.jl/releases/download/Raylib-v4.0.0+1/Raylib.v4.0.0.x86_64-apple-darwin.tar.gz"
[[Raylib]]
arch = "x86_64"
git-tree-sha1 = "19e7b410409bb3a93952f8cb119775e7f14fee6a"
libc = "glibc"
os = "linux"

    [[Raylib.download]]
    sha256 = "f5f8e881adb912903bd7f46c63205b580c03f5b6c8f445f8a5314b865dd769ab"
    url = "https://github.com/JuliaBinaryWrappers/Raylib_jll.jl/releases/download/Raylib-v4.0.0+1/Raylib.v4.0.0.x86_64-linux-gnu.tar.gz"
[[Raylib]]
arch = "x86_64"
git-tree-sha1 = "9455ad161eba453a68fc6d2edf1b4d68ffdf3b78"
libc = "musl"
os = "linux"

    [[Raylib.download]]
    sha256 = "5690ce4fd8243e17b57d37f834283ce30fedc4e92b5480704bda74dd8b89c61b"
    url = "https://github.com/JuliaBinaryWrappers/Raylib_jll.jl/releases/download/Raylib-v4.0.0+1/Raylib.v4.0.0.x86_64-linux-musl.tar.gz"
[[Raylib]]
arch = "x86_64"
git-tree-sha1 = "f4fe8dd9de3cc1e2ee53626bc2e256ec5cb84fe6"
os = "freebsd"

    [[Raylib.download]]
    sha256 = "505595f1ae76e97c43a66c22e906a558e287de49291e5987af9565de0e7d5790"
    url = "https://github.com/JuliaBinaryWrappers/Raylib_jll.jl/releases/download/Raylib-v4.0.0+1/Raylib.v4.0.0.x86_64-unknown-freebsd.tar.gz"
