[[Raylib]]
arch = "aarch64"
git-tree-sha1 = "9f002cde1ae450ce2ac25d43e825ddc8a5e17b3f"
os = "macos"

    [[Raylib.download]]
    sha256 = "b713fc3440c7c9c51163d05b0c47cfc856003cead26c962af7cc18dc8f7adb01"
    url = "https://github.com/JuliaBinaryWrappers/Raylib_jll.jl/releases/download/Raylib-v4.0.0+2/Raylib.v4.0.0.aarch64-apple-darwin.tar.gz"
[[Raylib]]
arch = "aarch64"
git-tree-sha1 = "5c068239e7710c3be2df04c390093d655c21ea1c"
libc = "glibc"
os = "linux"

    [[Raylib.download]]
    sha256 = "1e1b7f053d4e5d80b5d984066a661346a5482fbbec60bbfeb56c8c890bd81470"
    url = "https://github.com/JuliaBinaryWrappers/Raylib_jll.jl/releases/download/Raylib-v4.0.0+2/Raylib.v4.0.0.aarch64-linux-gnu.tar.gz"
[[Raylib]]
arch = "aarch64"
git-tree-sha1 = "4f518db04053ffcabcfc17743adfa39697fc90d2"
libc = "musl"
os = "linux"

    [[Raylib.download]]
    sha256 = "96b8651ba7f7788bfe698a32feba0d9fabe90a05e1fbafc54dd41b89107d39a3"
    url = "https://github.com/JuliaBinaryWrappers/Raylib_jll.jl/releases/download/Raylib-v4.0.0+2/Raylib.v4.0.0.aarch64-linux-musl.tar.gz"
[[Raylib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c6bba21afc878ff4e705ce56e0f36e79586a2586"
libc = "glibc"
os = "linux"

    [[Raylib.download]]
    sha256 = "c77bc0a0cc27bfddd6d66283ccdc764a08a89364fd20ea0f5127b612164201b5"
    url = "https://github.com/JuliaBinaryWrappers/Raylib_jll.jl/releases/download/Raylib-v4.0.0+2/Raylib.v4.0.0.armv7l-linux-gnueabihf.tar.gz"
[[Raylib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fe4ff25cc763088763339cb3f5e22e44607d8514"
libc = "musl"
os = "linux"

    [[Raylib.download]]
    sha256 = "3ea12109353de6d25125b549fa0d9582d007ffb9ba627f4b2a56df02c960907e"
    url = "https://github.com/JuliaBinaryWrappers/Raylib_jll.jl/releases/download/Raylib-v4.0.0+2/Raylib.v4.0.0.armv7l-linux-musleabihf.tar.gz"
[[Raylib]]
arch = "i686"
git-tree-sha1 = "48524a1d9c23ff06efdd4911355c954250038bad"
libc = "glibc"
os = "linux"

    [[Raylib.download]]
    sha256 = "2c28f7bb34096dd4c5721798319922566944947bf6533f4d7ae403a294607a9d"
    url = "https://github.com/JuliaBinaryWrappers/Raylib_jll.jl/releases/download/Raylib-v4.0.0+2/Raylib.v4.0.0.i686-linux-gnu.tar.gz"
[[Raylib]]
arch = "i686"
git-tree-sha1 = "c988c2f131e4485c0f46c470a44c9d4966e62793"
libc = "musl"
os = "linux"

    [[Raylib.download]]
    sha256 = "7bb9000ee1e61f25de3003a3c99fafd3accd41910c1c5f9fb6a1b9d879f0fa9b"
    url = "https://github.com/JuliaBinaryWrappers/Raylib_jll.jl/releases/download/Raylib-v4.0.0+2/Raylib.v4.0.0.i686-linux-musl.tar.gz"
[[Raylib]]
arch = "i686"
git-tree-sha1 = "7f6b2297a8d0e5e3c8dd993e30cff3ff826110b0"
os = "windows"

    [[Raylib.download]]
    sha256 = "0046618ae957cbaa711471d8f417c779aa8e17111611ce2a9c98fca34cf26eb9"
    url = "https://github.com/JuliaBinaryWrappers/Raylib_jll.jl/releases/download/Raylib-v4.0.0+2/Raylib.v4.0.0.i686-w64-mingw32.tar.gz"
[[Raylib]]
arch = "powerpc64le"
git-tree-sha1 = "81df49e6a934dd64f7635676b2a5529ea768f489"
libc = "glibc"
os = "linux"

    [[Raylib.download]]
    sha256 = "012650fb0eec6a9b91b5a366aef5fe92c6a548f7b932627e3198c336a4bba898"
    url = "https://github.com/JuliaBinaryWrappers/Raylib_jll.jl/releases/download/Raylib-v4.0.0+2/Raylib.v4.0.0.powerpc64le-linux-gnu.tar.gz"
[[Raylib]]
arch = "x86_64"
git-tree-sha1 = "9454acc7334153a317def706c072f53448fa5147"
os = "macos"

    [[Raylib.download]]
    sha256 = "b18f0347158ffde41a5922f31e5b9c3f27ba70a460365414eedbd7a47d3e0861"
    url = "https://github.com/JuliaBinaryWrappers/Raylib_jll.jl/releases/download/Raylib-v4.0.0+2/Raylib.v4.0.0.x86_64-apple-darwin.tar.gz"
[[Raylib]]
arch = "x86_64"
git-tree-sha1 = "43bf856bd341c937a4ef62a0db273d61985df75e"
libc = "glibc"
os = "linux"

    [[Raylib.download]]
    sha256 = "60ebfda58ad6f17da1d0e0048ca94391a80f8456914fcc3fbe0c9ddfd4288b14"
    url = "https://github.com/JuliaBinaryWrappers/Raylib_jll.jl/releases/download/Raylib-v4.0.0+2/Raylib.v4.0.0.x86_64-linux-gnu.tar.gz"
[[Raylib]]
arch = "x86_64"
git-tree-sha1 = "6c0dfcdadd47720f4d72e2315a2bf5506653cc36"
libc = "musl"
os = "linux"

    [[Raylib.download]]
    sha256 = "022626d3a73be466eb10fb962adf2d0233e8e0599ed0d743b628f206a54ec882"
    url = "https://github.com/JuliaBinaryWrappers/Raylib_jll.jl/releases/download/Raylib-v4.0.0+2/Raylib.v4.0.0.x86_64-linux-musl.tar.gz"
[[Raylib]]
arch = "x86_64"
git-tree-sha1 = "6bca20e69b1b407c470c384a5fcb18e9372ef003"
os = "freebsd"

    [[Raylib.download]]
    sha256 = "a460f158494f48fb67d1dddd0602a1dec8e863cd7331c0fa9a8d00b359a8a6a0"
    url = "https://github.com/JuliaBinaryWrappers/Raylib_jll.jl/releases/download/Raylib-v4.0.0+2/Raylib.v4.0.0.x86_64-unknown-freebsd.tar.gz"
[[Raylib]]
arch = "x86_64"
git-tree-sha1 = "e91f0c3bf8b387afe9aff9999a269653a3c82883"
os = "windows"

    [[Raylib.download]]
    sha256 = "84b5ada96af9b789121aa689b0ca0e81604b3309c8cbd638a780d6c5a7a2a5af"
    url = "https://github.com/JuliaBinaryWrappers/Raylib_jll.jl/releases/download/Raylib-v4.0.0+2/Raylib.v4.0.0.x86_64-w64-mingw32.tar.gz"
