# Autogenerated wrapper script for Raylib_jll for aarch64-apple-darwin
export libraylib

using GLFW_jll
JLLWrappers.@generate_wrapper_header("Raylib")
JLLWrappers.@declare_library_product(libraylib, "@rpath/libraylib.400.dylib")
function __init__()
    JLLWrappers.@generate_init_header(GLFW_jll)
    JLLWrappers.@init_library_product(
        libraylib,
        "lib/libraylib.4.0.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
